name: terraform formatter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
    - extraction/terraform/**

defaults:
  run:
    working-directory: ./extraction

jobs:
  terraform-formatter:
    runs-on: ubuntu-latest
    container: nikolaik/python-nodejs:python3.9-nodejs18-slim

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update packages and install make
        run: apt -y update && apt -y install make unzip

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9

      - name: Check terraform format
        run: make check-terraform-format
