name: tests

env:
    AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    AWS_REGION: ${{ secrets.AWS_REGION }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
    - extraction/**

defaults:
  run:
    working-directory: ./extraction

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: python:3.9.11-slim

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update packages and install make
        run: apt -y update && apt install -y make postgresql gcc libpq-dev

      - name: Install requirements
        run: pip install -r requirements/base.txt -r requirements/test.txt

      - name: Copy empty .env
        run: cp example.env .env

      - name: Pytest it
        run: pytest -s -vv
